### ISSUE TITLE
Error Loading Package

### ISSUE THREAD

**Issue by InteXX** [sajalverma17/GitBranchDiffer#41]
**Version Information :**
 - Visual Studio 2022 Professional, v17.4.3
 - Git Branch Differ v1.1.0

**Describe the Bug**
 - Intermittent error loading package after extensions list export:

![image](https://user-images.githubusercontent.com/10966749/215291543-4f145c2e-539f-4a94-bf89-d1e0691a1283.png)

**To Reproduce**
1. Install the [Extension Manager 2022](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ExtensionManager2022) extension
2. Restart Visual Studio, choosing *Continue without code...*
3. On the Extensions menu, choose `Import and Export Extensions > Export Extensions...`
4. After the export file is saved, note the error message above

**Expected Behavior**
The package should load without error.

**Screenshots**
See above. 

**Error Log**
https://gist.github.com/InteXX/ef15b0e352a7f8b7c1cf7ae2a72318e1

*Relevant part*
```
  <entry>
    <record>2804</record>
    <time>2023/01/28 21:18:44.390</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [GitBranchDifferPackage]</description>
    <guid>{156FCEC6-25AC-4279-91CC-BBE2E4EA8C14}</guid>
  </entry>
  <entry>
    <record>2805</record>
    <time>2023/01/28 21:18:44.427</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [DiffPackage]</description>
    <guid>{8DE3F279-5341-44B9-AFD8-F429920DF4AE}</guid>
  </entry>
  <entry>
    <record>2806</record>
    <time>2023/01/28 21:18:44.430</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [DiffPackage]</description>
    <guid>{8DE3F279-5341-44B9-AFD8-F429920DF4AE}</guid>
  </entry>
  <entry>
    <record>2807</record>
    <time>2023/01/28 21:18:44.436</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [GitBranchDifferPackage]Source: &apos;mscorlib&apos; Description: The path is not of a legal form.&#x000D;&#x000A;System.ArgumentException: The path is not of a legal form.&#x000D;&#x000A;   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)&#x000D;&#x000A;   at System.IO.Path.InternalGetDirectoryName(String path)&#x000D;&#x000A;   at BranchDiffer.VS.Shared.GitBranchDifferPackage.SetSolutionInfo()&#x000D;&#x000A;   at BranchDiffer.VS.Shared.GitBranchDifferPackage.&lt;InitializeAsync&gt;d__4.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>
    <guid>{156FCEC6-25AC-4279-91CC-BBE2E4EA8C14}</guid>
    <hr>0x80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
  </entry>
```
*Sanitized stack trace*
```
SetSite failed for package [GitBranchDifferPackage]Source: 'mscorlib' Description: The path is not of a legal form.
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at BranchDiffer.VS.Shared.GitBranchDifferPackage.SetSolutionInfo()
   at BranchDiffer.VS.Shared.GitBranchDifferPackage.<InitializeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
```

**Additional Context**
Visual Studio running without any solutions/projects loaded (*Continue without code...*)

**Comment by sajalverma17** [comment]
Turned out to be a quick fix, now pushed to the latest CI build. I'll make a release in coming days.

**Comment by InteXX** [comment]
Goodness, that was quick!

It appears it may have been related to having VS open without any solution/file loaded. Am I correct?

**Comment by sajalverma17** [comment]
That's correct. Having VS open any file without a Solution will reproduce this bug.

VS actually loads a "dummy" solution (called Solution1 visible in Solution Explorer) when we open a file in VS without a solution. And that triggers VS to initialize this extension with a non-existent solution.

The Extension Manager 2022 opens up the .vsext file right after the export, and since you opened VS without a Solution initially ("Continue without code"), that .vsext file triggers this bug.

**Comment by InteXX** [comment]
That's good to know, thanks.

Keep up the good work!

**Comment by sajalverma17** [comment]
I've released the fix for this bug, cheers!

**Comment by InteXX** [comment]
Thanks 🙂
